### PR TITLE
Assorted v2 cleanup

### PR DESCRIPTION
**Pull request by cespare**
This is followup for #15.

### CODE REVIEW

**Comment by cespare** [comment]
@ongardie-ebay this PR is mostly just naming/doc/comment changes along with some minor refactoring. The only thing I really added was some tests that will fail if code that shouldn't allocate does. I tend to prefer tests (rather than relying on benchmarks) to lock in that behavior when possible.

**Comment by cespare** [comment]
Don't you mean a slight perf improvement?

I see this change too; looks like it's due to the changes to the benchmark code in 26315204797e07a5e9a825080a37ababf62404d3.

**Comment by cespare** [comment]
Thanks for the review Diego.

**Comment by ongardie-ebay** [comment]
> Don't you mean a slight perf improvement?

Oops, yep, can't complain then.

**Pull request merged**
